const weeks=[{week:1,short:15,medium:30,long:45,note:'Start controlled'},{week:2,short:16,medium:32,long:48,note:'Small build'},{week:3,short:12,medium:24,long:36,note:'Deload'},{week:4,short:18,medium:36,long:54,note:'Build carefully'},{week:5,short:20,medium:40,long:60,note:'First platform'},{week:6,short:15,medium:30,long:45,note:'Deload'},{week:7,short:20,medium:40,long:60,note:'Consolidate'},{week:8,short:20,medium:40,long:60,note:'Repeat for durability'},{week:9,short:16,medium:32,long:48,note:'Deload'},{week:10,short:22,medium:44,long:66,note:'Optional build if green'},{week:11,short:22,medium:44,long:66,note:'Repeat if stable'},{week:12,short:18,medium:36,long:54,note:'Deload and reassess'}];
const days=[{day:'Mon',run:'Short',bike:'',strength:'Upper strength',calf:''},{day:'Tue',run:'Medium',bike:'Bike 1 · easy Zone 2',strength:'',calf:'Calf A · heavy slow'},{day:'Wed',run:'Short',bike:'',strength:'Leg strength',calf:''},{day:'Thu',run:'',bike:'Bike 2 · easy cadence',strength:'',calf:'Calf B · heavy slow'},{day:'Fri',run:'Medium',bike:'',strength:'',calf:''},{day:'Sat',run:'Long',bike:'',strength:'',calf:'Optional isometrics'},{day:'Sun',run:'Short',bike:'Bike 3 · long easy',strength:'',calf:''}];
let logs=JSON.parse(localStorage.getItem('tbLogs')||'{}');
let strength=JSON.parse(localStorage.getItem('tbStrength')||'{}');
let strengthLogs=JSON.parse(localStorage.getItem('tbStrengthLogs')||'[]');
const strengthExercises={Lower:['Squat','Romanian Deadlift','Split Squat','Hamstring Curl'],Upper:['Bench Press','Seated Row','Lat Pulldown','Shoulder Press'],Calf:['Standing Calf Raise','Seated Calf Raise','Single-leg Calf Raise','Tibialis Raise']};
const $=id=>document.getElementById(id);const weekNo=()=>Number(localStorage.getItem('tbWeek')||1);const dayNo=()=>Number(localStorage.getItem('tbDay')||0);const bikeLong=()=>Number(localStorage.getItem('tbLongBike')||90);const week=()=>weeks.find(w=>w.week===weekNo())||weeks[0];const key=(w,d)=>`${w}-${days[d].day}`;
const cls={pill:'inline-flex items-center justify-center rounded-full px-3 py-1 text-[11px] font-black uppercase tracking-wide'};
function runMin(w,t){return t==='Short'?w.short:t==='Medium'?w.medium:t==='Long'?w.long:0}function bikeMin(item){return item.bike.includes('Bike 1')?55:item.bike.includes('Bike 2')?55:item.bike.includes('Bike 3')?bikeLong():0}
function stat(e){if(!e)return{text:'Not logged',state:'neutral',hint:'Log today to guide tomorrow.'};let p=Number(e.pain||0),s=Number(e.stiff||0);if(e.flare||e.stride||p>=4||s>=4)return{text:'Deload',state:'red',hint:'Reduce load and reassess before progressing.'};if(p===3||s===3)return{text:'Repeat',state:'amber',hint:'Repeat this week until symptoms settle.'};return{text:'Green',state:'green',hint:'Progress only as planned.'}}
function statusClasses(state){return state==='red'?'bg-red-500/15 text-red-200 ring-red-300/15':state==='amber'?'bg-amber-400/15 text-amber-200 ring-amber-300/15':state==='green'?'bg-emerald-400/15 text-emerald-200 ring-emerald-300/15':'bg-white/10 text-zinc-300 ring-white/10'}
function summary(item,w){let parts=[],r=runMin(w,item.run),b=bikeMin(item);if(r)parts.push(`${item.run} run · ${r} min easy`);if(b)parts.push(`${item.bike} · ${b} min`);if(item.strength)parts.push(item.strength);if(item.calf)parts.push(item.calf);return parts.join(' + ')||'Recovery focus'}
function rows(){let w=week();return days.map((item,i)=>{let e=logs[key(w.week,i)],r=runMin(w,item.run),b=bikeMin(item);return{...item,index:i,entry:e,status:stat(e),run:r,bike:b,summary:summary(item,w)}})}
function controls(){let ws=$('weekSelect'),ds=$('daySelect'),lb=$('longBike');if(ws){ws.innerHTML=weeks.map(w=>`<option value="${w.week}">Week ${w.week}</option>`).join('');ws.value=weekNo();ws.onchange=()=>{localStorage.setItem('tbWeek',ws.value);render()}}if(ds){ds.innerHTML=days.map((d,i)=>`<option value="${i}">${d.day}</option>`).join('');ds.value=dayNo();ds.onchange=()=>{localStorage.setItem('tbDay',ds.value);render()}}if(lb){lb.value=bikeLong();lb.onchange=()=>{localStorage.setItem('tbLongBike',lb.value);render()}}document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('text-[#ff6b2b]',a.dataset.nav===document.body.dataset.page))}
function worst(rs){let sev={neutral:0,green:1,amber:2,red:3};return rs.reduce((m,r)=>sev[r.status.state]>sev[m.state]?r.status:m,{text:'Not logged',state:'neutral',hint:'Log today to guide tomorrow.'})}
function shared(){let rs=rows(),w=week(),ws=worst(rs),today=rs[dayNo()]||rs[0],next=rs[(dayNo()+1)%7];if($('todayTitle'))$('todayTitle').textContent=today.day;if($('todayDetail'))$('todayDetail').textContent=today.summary;if($('nextTitle'))$('nextTitle').textContent=next.day;if($('nextDetail'))$('nextDetail').textContent=next.summary;if($('recommendationText'))$('recommendationText').textContent=ws.state==='red'?'Deload':ws.state==='amber'?'Repeat week':ws.state==='green'?'Progress as planned':'Log today';if($('recommendationHint'))$('recommendationHint').textContent=ws.hint;if($('readyText'))$('readyText').textContent=ws.text;if($('readyHint'))$('readyHint').textContent=ws.hint;if($('readyPill')){$('readyPill').className=`${cls.pill} ${statusClasses(ws.state)}`;$('readyPill').textContent=ws.text}if($('weekTitle'))$('weekTitle').textContent=`Week ${w.week}`;if($('weekHint'))$('weekHint').textContent=`${w.note} · ${w.short}/${w.medium}/${w.long} min run split.`}
function plan(){let el=$('planList');if(!el)return;el.innerHTML=rows().map(r=>`<article class="rounded-[28px] bg-[#202428] p-5 ring-1 ring-white/5"><h3 class="text-2xl font-black">${r.day}</h3><p class="mt-1 text-sm text-zinc-400">${r.summary}</p><a href="log.html" onclick="localStorage.setItem('tbDay','${r.index}')" class="mt-4 flex min-h-12 items-center justify-center rounded-full bg-[#ff6b2b] text-sm font-black text-white">Log</a></article>`).join('')}
function logPage(){if(!$('logTitle'))return;let row=rows()[dayNo()]||rows()[0],e=row.entry||{};$('logTitle').textContent=row.day;$('logDetail').textContent=row.summary;['completed','flare','stride'].forEach(id=>{if($(id))$(id).checked=!!e[id]});['actual','rpe','pain','stiff','notes'].forEach(id=>{if($(id))$(id).value=e[id]||''});if($('save'))$('save').onclick=()=>{logs[key(weekNo(),dayNo())]={completed:$('completed')?.checked,actual:$('actual')?.value,rpe:$('rpe')?.value,pain:$('pain')?.value,stiff:$('stiff')?.value,flare:$('flare')?.checked,stride:$('stride')?.checked,notes:$('notes')?.value};localStorage.setItem('tbLogs',JSON.stringify(logs));render()}}
function progress(){if(!$('disciplineChart'))return}
function strengthVolume(log){return Number(log.weight||0)*Number(log.sets||0)*Number(log.reps||0)}
function getStrengthLogsForExercise(exercise){return strengthLogs.filter(log=>log.exercise===exercise)}
function getLastStrengthLog(exercise){let list=getStrengthLogsForExercise(exercise);return list.length?list[list.length-1]:null}
function getBestStrengthVolume(exercise){let list=getStrengthLogsForExercise(exercise);return list.length?Math.max(...list.map(strengthVolume)):0}
function getNextStrengthTarget(last){if(!last)return'Not logged';let weight=Number(last.weight||0),sets=Number(last.sets||0),reps=Number(last.reps||0);return`${weight} kg · ${sets} × ${reps+1}`}
function populateStrengthExerciseSelect(category,selectedExercise){let select=$('strengthExercise');if(!select)return;let exercises=strengthExercises[category]||[];select.innerHTML=exercises.map(exercise=>`<option value="${exercise}">${exercise}</option>`).join('');if(selectedExercise)select.value=selectedExercise}
window.setStrengthCategory=function(category){localStorage.setItem('tbStrengthCategory',category);renderStrengthPage()}
window.openStrengthLog=function(exercise,category){let categorySelect=$('strengthCategory'),title=$('strengthFormTitle'),pill=$('strengthFormCategoryPill');if(!categorySelect)return;categorySelect.value=category;populateStrengthExerciseSelect(category,exercise);if(title)title.textContent=exercise;if(pill)pill.textContent=category;let last=getLastStrengthLog(exercise);if($('strengthWeight'))$('strengthWeight').value=last?last.weight:'';if($('strengthSets'))$('strengthSets').value=last?last.sets:'';if($('strengthReps'))$('strengthReps').value=last?last.reps:'';$('strengthFormCard')?.scrollIntoView({behavior:'smooth',block:'start'})}
function saveStrengthLog(){let exercise=$('strengthExercise')?.value,category=$('strengthCategory')?.value,weight=Number($('strengthWeight')?.value||0),sets=Number($('strengthSets')?.value||0),reps=Number($('strengthReps')?.value||0);if(!exercise||!category||!sets||!reps)return;strengthLogs.push({exercise,category,weight,sets,reps,volume:weight*sets*reps,date:new Date().toISOString()});localStorage.setItem('tbStrengthLogs',JSON.stringify(strengthLogs));let btn=$('strengthSave');if(btn){btn.textContent='Saved';setTimeout(()=>btn.textContent='Save',700)}renderStrengthPage()}
function renderStrengthTabs(activeCategory){document.querySelectorAll('.strength-tab').forEach(button=>{let active=button.dataset.strengthCategory===activeCategory;button.className=active?'strength-tab flex min-h-12 shrink-0 touch-manipulation items-center rounded-full border border-[#ff6b2b] bg-[#ff6b2b]/10 px-5 text-sm font-black text-[#ff6b2b] transition hover:bg-[#ff6b2b]/15 focus:outline-none focus:ring-2 focus:ring-[#ff6b2b]/70 active:scale-[.98]':'strength-tab flex min-h-12 shrink-0 touch-manipulation items-center rounded-full border border-white/25 px-5 text-sm font-black text-zinc-300 transition hover:bg-white/5 hover:text-white focus:outline-none focus:ring-2 focus:ring-[#ff6b2b]/70 active:scale-[.98]';button.onclick=()=>setStrengthCategory(button.dataset.strengthCategory)})}
function renderStrengthList(category){let list=$('strengthList');if(!list)return;let exercises=strengthExercises[category]||[];list.innerHTML=exercises.map(exercise=>{let last=getLastStrengthLog(exercise),best=getBestStrengthVolume(exercise),lastVolume=last?strengthVolume(last):0,lastText=last?`${last.weight} kg · ${last.sets} × ${last.reps}`:'Not logged',volumeText=last?`${lastVolume.toLocaleString()} kg`:'0 kg',bestText=best?`${best.toLocaleString()} kg`:'0 kg',nextText=getNextStrengthTarget(last);return`<article class="rounded-[28px] bg-[#202428] p-5 shadow-[0_22px_70px_rgba(0,0,0,.34)] ring-1 ring-white/5"><div class="mb-5 flex items-start justify-between gap-4"><div><h2 class="text-2xl font-black tracking-tight">${exercise}</h2><span class="mt-2 inline-flex rounded-full bg-white/10 px-3 py-1 text-[11px] font-black uppercase tracking-wide text-zinc-300">${category}</span></div><button type="button" onclick="openStrengthLog('${exercise}','${category}')" class="min-h-11 touch-manipulation rounded-full bg-[#ff6b2b] px-4 text-sm font-black text-white shadow-[0_12px_28px_rgba(255,107,43,.28)] transition hover:bg-[#ff7a3d] focus:outline-none focus:ring-2 focus:ring-[#ff6b2b]/70 active:scale-[.98]">Log</button></div><div class="grid grid-cols-2 gap-3"><div class="rounded-[22px] bg-white/7 p-3 ring-1 ring-white/5"><p class="text-xs font-bold text-zinc-500">Last</p><p class="mt-1 text-sm font-black text-white">${lastText}</p></div><div class="rounded-[22px] bg-white/7 p-3 ring-1 ring-white/5"><p class="text-xs font-bold text-zinc-500">Volume</p><p class="mt-1 text-sm font-black text-white">${volumeText}</p></div><div class="rounded-[22px] bg-white/7 p-3 ring-1 ring-white/5"><p class="text-xs font-bold text-zinc-500">Best</p><p class="mt-1 text-sm font-black text-white">${bestText}</p></div><div class="rounded-[22px] bg-white/7 p-3 ring-1 ring-white/5"><p class="text-xs font-bold text-zinc-500">Next</p><p class="mt-1 text-sm font-black text-white">${nextText}</p></div></div></article>`}).join('')}
function renderStrengthPage(){if(!$('strengthList'))return;let activeCategory=localStorage.getItem('tbStrengthCategory')||'Lower';renderStrengthTabs(activeCategory);renderStrengthList(activeCategory);populateStrengthExerciseSelect(activeCategory);let categorySelect=$('strengthCategory'),exerciseSelect=$('strengthExercise');if(categorySelect){categorySelect.value=activeCategory;categorySelect.onchange=()=>{localStorage.setItem('tbStrengthCategory',categorySelect.value);populateStrengthExerciseSelect(categorySelect.value);renderStrengthPage()}}if(exerciseSelect){let selected=exerciseSelect.value,title=$('strengthFormTitle');if(title&&selected)title.textContent=selected;exerciseSelect.onchange=()=>{let title=$('strengthFormTitle');if(title)title.textContent=exerciseSelect.value}}let pill=$('strengthFormCategoryPill');if(pill)pill.textContent=activeCategory;let save=$('strengthSave');if(save)save.onclick=saveStrengthLog}
function bodyPage(){renderStrengthPage()}
function render(){controls();shared();plan();logPage();progress();bodyPage()}
document.addEventListener('DOMContentLoaded',render);
